### ISSUE TITLE
Error: undeclared identifier: 'PKNORMAL_ROUTINE'

### ISSUE THREAD

**Issue by OffenseTeacher** [ajpc500/NimlineWhispers#4]
Hey :)

Been trying to do QueueApc for a few days. I always get the following error on compilation:
`Error: undeclared identifier: 'PKNORMAL_ROUTINE`

Even using latest pull from NimlineWhispers and the latest Nim example you just published about this exact type of injection

It refers to the proc in syscalls.nim:
`proc NtQueueApcThread*(ThreadHandle: HANDLE, ApcRoutine: PKNORMAL_ROUTINE, ...`

and the following code in the main file:
```
status = NtQueueApcThread(
        tHandle, 
        cast[PKNORMAL_ROUTINE](ds), 
        ds, 
        NULL, 
        NULL);
```

How would you approach this error?

Thanks!

**Comment by ajpc500** [comment]
Hey!

Just to check you've got the latest `syscalls.nim` file in the NimExamples folder?

The `PKNORMAL_ROUTINE` identifier should be defined [there](https://github.com/ajpc500/NimExamples/blob/main/src/syscalls.nim#L17). 

Worth noting that NimlineWhispers will only create the inline assembly functions for you atm, the definition of structs etc, will have to be done manually (at least for now). E.g. `KNORMAL_ROUTINE` and the ptr `PKNORMAL_ROUTINE` are defined [here](https://github.com/ajpc500/NimlineWhispers/blob/main/Syscalls.h#L50) and [here](https://github.com/ajpc500/NimlineWhispers/blob/main/Syscalls.h#L509) respectively, and require converting to nim syntax for inclusion.

**Comment by OffenseTeacher** [comment]
Ahh! Thanks. Totally missed that file. :)
